// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Simple greeting function
Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Calculate Fibonacci number
Future<BigInt> calculateFibonacci({required int n}) =>
    RustLib.instance.api.crateApiSimpleCalculateFibonacci(n: n);

/// Add two numbers (example with multiple parameters)
Future<PlatformInt64> addNumbers({
  required PlatformInt64 a,
  required PlatformInt64 b,
}) => RustLib.instance.api.crateApiSimpleAddNumbers(a: a, b: b);
